export const SET_OPTIONS = "SET_OPTIONS";
export const FETCH_LISTINGS = "FETCH_LISTINGS"
export const FETCHING_LISTINGS = "FETCHING_LISTINGS"
export const FETCH_LISTINGS_FAILED = "FETCH_LISTINGS_FAILED"
export const VIEW_CATOLOG = "VIEW_CATOLOG"
export const SHUFFLE_LISTINGS = "SHUFFLE_LISTINGS"
export const SET_SHOWING_FILTERS = "SET_SHOWING_FILTERS"

export const FETCH_PARTNERS = "FETCH_PARTNERS"
export const FETCHING_PARTNERS = "FETCHING_PARTNERS"
export const FETCH_PARTNERS_FAILED = "FETCH_PARTNERS_FAILED"

export const ADD_CLICK = "ADD_CLICK"
export const ADD_IMPRESSION = "ADD_IMPRESSION"
export const SUBMIT_METRICS = "SUBMIT_METRICS"
export const SUBMIT_METRICS_FAILED = "SUBMIT_METRICS_FAILED"
export const SET_METRICS = "SET_METRICS"